# Generated by Django 4.1.7 on 2023-04-12 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_auto_20230412_1746"),
    ]

    operations = [
             migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
